version : '3'

services:
  mysql:
    image: mysql:latest
    container_name: dev_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_restaurant
    volumes:
      - db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dev_pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8183:80

  web:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - mysql
    container_name: web_laravel
    command: "php artisan serve --host=0.0.0.0 --port=8000"

volumes:
  db-data:
